routes:
	# user api
 user:
   POST register: User.register
   POST login: User.login
   POST logout: User.logout

 POST room: Room.create
 GET room: Room.all
 GET room/user: Room.listForUser
 GET room/:location: Room.listForLocation